const gameSummary = [
    {"Home":"GB","Away":"CHI","HomeScore":"24.5","AwayScore":"21.5","HomeSnaps":"54","AwaySnaps":"60","LYHomePassDVOA":"28","LYHomeRushDVOA":"23","LYOppPassDVOA":"1","LYOppRushDVOA":"2","TYHomePassDVOA":"28","TYHomeRushDVOA":"23","TYOppPassDVOA":"1","TYOppRushDVOA":"2"},
    {"Home":"TEN","Away":"CLE","HomeScore":"25.5","AwayScore":"20","HomeSnaps":"59","AwaySnaps":"59","LYHomePassDVOA":"21","LYHomeRushDVOA":"15","LYOppPassDVOA":"7","LYOppRushDVOA":"25","TYHomePassDVOA":"21","TYHomeRushDVOA":"15","TYOppPassDVOA":"7","TYOppRushDVOA":"25"},
    {"Home":"BAL","Away":"MIA","HomeScore":"16.25","AwayScore":"21.25","HomeSnaps":"71","AwaySnaps":"72","LYHomePassDVOA":"3","LYHomeRushDVOA":"6","LYOppPassDVOA":"23","LYOppRushDVOA":"24","TYHomePassDVOA":"3","TYHomeRushDVOA":"6","TYOppPassDVOA":"23","TYOppRushDVOA":"24"},
    {"Home":"ATL","Away":"MIN","HomeScore":"25.75","AwayScore":"21.75","HomeSnaps":"55","AwaySnaps":"69","LYHomePassDVOA":"29","LYHomeRushDVOA":"30","LYOppPassDVOA":"5","LYOppRushDVOA":"11","TYHomePassDVOA":"29","TYHomeRushDVOA":"30","TYOppPassDVOA":"5","TYOppRushDVOA":"11"},
    {"Home":"BUF","Away":"NYJ","HomeScore":"20.75","AwayScore":"17.75","HomeSnaps":"71","AwaySnaps":"70","LYHomePassDVOA":"2","LYHomeRushDVOA":"14","LYOppPassDVOA":"18","LYOppRushDVOA":"21","TYHomePassDVOA":"2","TYHomeRushDVOA":"14","TYOppPassDVOA":"18","TYOppRushDVOA":"21"},
    {"Home":"WAS","Away":"PHI","HomeScore":"27.75","AwayScore":"18.75","HomeSnaps":"60","AwaySnaps":"63","LYHomePassDVOA":"11","LYHomeRushDVOA":"28","LYOppPassDVOA":"15","LYOppRushDVOA":"9","TYHomePassDVOA":"11","TYHomeRushDVOA":"28","TYOppPassDVOA":"15","TYOppRushDVOA":"9"},
    {"Home":"LAR","Away":"CAR","HomeScore":"24","AwayScore":"27","HomeSnaps":"63","AwaySnaps":"58","LYHomePassDVOA":"9","LYHomeRushDVOA":"27","LYOppPassDVOA":"24","LYOppRushDVOA":"18","TYHomePassDVOA":"9","TYHomeRushDVOA":"27","TYOppPassDVOA":"24","TYOppRushDVOA":"18"},
    {"Home":"KC","Away":"JAC","HomeScore":"24.25","AwayScore":"28.25","HomeSnaps":"54","AwaySnaps":"66","LYHomePassDVOA":"12","LYHomeRushDVOA":"32","LYOppPassDVOA":"6","LYOppRushDVOA":"7","TYHomePassDVOA":"12","TYHomeRushDVOA":"32","TYOppPassDVOA":"6","TYOppRushDVOA":"7"},
    {"Home":"IND","Away":"LAC","HomeScore":"26.25","AwayScore":"19.25","HomeSnaps":"75","AwaySnaps":"61","LYHomePassDVOA":"20","LYHomeRushDVOA":"4","LYOppPassDVOA":"10","LYOppRushDVOA":"10","TYHomePassDVOA":"20","TYHomeRushDVOA":"4","TYOppPassDVOA":"10","TYOppRushDVOA":"10"},
    {"Home":"CIN","Away":"SEA","HomeScore":"26.5","AwayScore":"17","HomeSnaps":"71","AwaySnaps":"68","LYHomePassDVOA":"25","LYHomeRushDVOA":"26","LYOppPassDVOA":"14","LYOppRushDVOA":"17","TYHomePassDVOA":"25","TYHomeRushDVOA":"26","TYOppPassDVOA":"14","TYOppRushDVOA":"17"},
    {"Home":"NYG","Away":"DAL","HomeScore":"26.25","AwayScore":"19.25","HomeSnaps":"57","AwaySnaps":"52","LYHomePassDVOA":"26","LYHomeRushDVOA":"20","LYOppPassDVOA":"16","LYOppRushDVOA":"5","TYHomePassDVOA":"26","TYHomeRushDVOA":"20","TYOppPassDVOA":"16","TYOppRushDVOA":"5"},
    {"Home":"DET","Away":"ARI","HomeScore":"22.5","AwayScore":"25","HomeSnaps":"69","AwaySnaps":"65","LYHomePassDVOA":"31","LYHomeRushDVOA":"13","LYOppPassDVOA":"8","LYOppRushDVOA":"29","TYHomePassDVOA":"31","TYHomeRushDVOA":"13","TYOppPassDVOA":"8","TYOppRushDVOA":"29"},
    {"Home":"SF","Away":"TB","HomeScore":"25","AwayScore":"24","HomeSnaps":"57","AwaySnaps":"71","LYHomePassDVOA":"27","LYHomeRushDVOA":"12","LYOppPassDVOA":"30","LYOppRushDVOA":"31","TYHomePassDVOA":"27","TYHomeRushDVOA":"12","TYOppPassDVOA":"30","TYOppRushDVOA":"31"},
    {"Home":"PIT","Away":"NE","HomeScore":"28.75","AwayScore":"22.75","HomeSnaps":"75","AwaySnaps":"53","LYHomePassDVOA":"17","LYHomeRushDVOA":"8","LYOppPassDVOA":"13","LYOppRushDVOA":"19","TYHomePassDVOA":"17","TYHomeRushDVOA":"8","TYOppPassDVOA":"13","TYOppRushDVOA":"19"},
    {"Home":"HOU","Away":"NO","HomeScore":"30.25","AwayScore":"23.25","HomeSnaps":"51","AwaySnaps":"74","LYHomePassDVOA":"19","LYHomeRushDVOA":"1","LYOppPassDVOA":"22","LYOppRushDVOA":"3","TYHomePassDVOA":"19","TYHomeRushDVOA":"1","TYOppPassDVOA":"22","TYOppRushDVOA":"3"},
    {"Home":"DEN","Away":"OAK","HomeScore":"22.5","AwayScore":"21","HomeSnaps":"73","AwaySnaps":"71","LYHomePassDVOA":"4","LYHomeRushDVOA":"16","LYOppPassDVOA":"32","LYOppRushDVOA":"22","TYHomePassDVOA":"4","TYHomeRushDVOA":"16","TYOppPassDVOA":"32","TYOppRushDVOA":"22"}
    ]
    

    
    export default gameSummary