const gameSummary = [
    {"Away":"SF","Home":"CIN","AwayScore":"21.5","HomeScore":"23","AwaySnaps":"64.37","HomeSnaps":"62.05","LYOppPassDVOA":"27","LYOppRushDVOA":"12","LYHomePassDVOA":"25","LYHomeRushDVOA":"26","TYHOppPassDVOA":"1","TYOppRushDVOA":"21","TYHomePassDVOA":"14","TYHomeRushDVOA":"10"},
    {"Away":"LAC","Home":"DET","AwayScore":"25.25","HomeScore":"22.75","AwaySnaps":"59.49","HomeSnaps":"63.9","LYOppPassDVOA":"10","LYOppRushDVOA":"10","LYHomePassDVOA":"31","LYHomeRushDVOA":"13","TYHOppPassDVOA":"21","TYOppRushDVOA":"31","TYHomePassDVOA":"7","TYHomeRushDVOA":"15"},
    {"Away":"MIN","Home":"GB","AwayScore":"21","HomeScore":"23.5","AwaySnaps":"60.58","HomeSnaps":"63.21","LYOppPassDVOA":"5","LYOppRushDVOA":"11","LYHomePassDVOA":"28","LYHomeRushDVOA":"23","TYHOppPassDVOA":"12","TYOppRushDVOA":"7","TYHomePassDVOA":"4","TYHomeRushDVOA":"6"},
    {"Away":"IND","Home":"TEN","AwayScore":"21","HomeScore":"24","AwaySnaps":"61.46","HomeSnaps":"59.64","LYOppPassDVOA":"20","LYOppRushDVOA":"4","LYHomePassDVOA":"21","LYHomeRushDVOA":"15","TYHOppPassDVOA":"19","TYOppRushDVOA":"30","TYHomePassDVOA":"2","TYHomeRushDVOA":"17"},
    {"Away":"NE","Home":"MIA","AwayScore":"33","HomeScore":"14.5","AwaySnaps":"66.57","HomeSnaps":"59.18","LYOppPassDVOA":"13","LYOppRushDVOA":"19","LYHomePassDVOA":"23","LYHomeRushDVOA":"24","TYHOppPassDVOA":"9","TYOppRushDVOA":"5","TYHomePassDVOA":"32","TYHomeRushDVOA":"24"},
    {"Away":"BUF","Home":"NYG","AwayScore":"22.75","HomeScore":"20.75","AwaySnaps":"64.95","HomeSnaps":"63.84","LYOppPassDVOA":"2","LYOppRushDVOA":"14","LYHomePassDVOA":"26","LYHomeRushDVOA":"20","TYHOppPassDVOA":"8","TYOppRushDVOA":"12","TYHomePassDVOA":"31","TYHomeRushDVOA":"13"},
    {"Away":"SEA","Home":"PIT","AwayScore":"21.5","HomeScore":"25","AwaySnaps":"60.41","HomeSnaps":"66.55","LYOppPassDVOA":"14","LYOppRushDVOA":"17","LYHomePassDVOA":"17","LYHomeRushDVOA":"8","TYHOppPassDVOA":"13","TYOppRushDVOA":"2","TYHomePassDVOA":"28","TYHomeRushDVOA":"14"},
    {"Away":"DAL","Home":"WAS","AwayScore":"25.5","HomeScore":"21","AwaySnaps":"60.77","HomeSnaps":"61.62","LYOppPassDVOA":"16","LYOppRushDVOA":"5","LYHomePassDVOA":"11","LYHomeRushDVOA":"28","TYHOppPassDVOA":"16","TYOppRushDVOA":"26","TYHomePassDVOA":"25","TYHomeRushDVOA":"16"},
    {"Away":"ARI","Home":"BAL","AwayScore":"16.75","HomeScore":"30.25","AwaySnaps":"62.65","HomeSnaps":"61.73","LYOppPassDVOA":"8","LYOppRushDVOA":"29","LYHomePassDVOA":"3","LYHomeRushDVOA":"6","TYHOppPassDVOA":"23","TYOppRushDVOA":"9","TYHomePassDVOA":"3","TYHomeRushDVOA":"1"},
    {"Away":"JAC","Home":"HOU","AwayScore":"17.5","HomeScore":"26","AwaySnaps":"60.4","HomeSnaps":"63.91","LYOppPassDVOA":"6","LYOppRushDVOA":"7","LYHomePassDVOA":"19","LYHomeRushDVOA":"1","TYHOppPassDVOA":"27","TYOppRushDVOA":"25","TYHomePassDVOA":"24","TYHomeRushDVOA":"20"},
    {"Away":"KC","Home":"OAK","AwayScore":"30","HomeScore":"22","AwaySnaps":"63.04","HomeSnaps":"60.25","LYOppPassDVOA":"12","LYOppRushDVOA":"32","LYHomePassDVOA":"32","LYHomeRushDVOA":"22","TYHOppPassDVOA":"26","TYOppRushDVOA":"18","TYHomePassDVOA":"17","TYHomeRushDVOA":"11"},
    {"Away":"CHI","Home":"DEN","AwayScore":"21.25","HomeScore":"19.25","AwaySnaps":"63.43","HomeSnaps":"59.21","LYOppPassDVOA":"1","LYOppRushDVOA":"2","LYHomePassDVOA":"4","LYHomeRushDVOA":"16","TYHOppPassDVOA":"15","TYOppRushDVOA":"4","TYHomePassDVOA":"30","TYHomeRushDVOA":"19"},
    {"Away":"NO","Home":"LAR","AwayScore":"25.5","HomeScore":"28.5","AwaySnaps":"62.49","HomeSnaps":"63.56","LYOppPassDVOA":"22","LYOppRushDVOA":"3","LYHomePassDVOA":"9","LYHomeRushDVOA":"27","TYHOppPassDVOA":"22","TYOppRushDVOA":"32","TYHomePassDVOA":"5","TYHomeRushDVOA":"28"},
    {"Away":"PHI","Home":"ATL","AwayScore":"26","HomeScore":"25","AwaySnaps":"62.24","HomeSnaps":"64.71","LYOppPassDVOA":"15","LYOppRushDVOA":"9","LYHomePassDVOA":"29","LYHomeRushDVOA":"30","TYHOppPassDVOA":"29","TYOppRushDVOA":"3","TYHomePassDVOA":"18","TYHomeRushDVOA":"23"},
    {"Away":"CLE","Home":"NYJ","AwayScore":"21.75","HomeScore":"24.25","AwaySnaps":"62.57","HomeSnaps":"65.16","LYOppPassDVOA":"7","LYOppRushDVOA":"25","LYHomePassDVOA":"18","LYHomeRushDVOA":"21","TYHOppPassDVOA":"20","TYOppRushDVOA":"27","TYHomePassDVOA":"6","TYHomeRushDVOA":"22"},
    {"Away":"TB","Home":"CAR","AwayScore":"21.75","HomeScore":"28.25","AwaySnaps":"65.12","HomeSnaps":"61.87","LYOppPassDVOA":"30","LYOppRushDVOA":"31","LYHomePassDVOA":"24","LYHomeRushDVOA":"18","TYHOppPassDVOA":"10","TYOppRushDVOA":"8","TYHomePassDVOA":"11","TYHomeRushDVOA":"29"}
    ]
    

    
    export default gameSummary