const gameSummary = [
    {"Away":"GB","Home":"CHI","AwayScore":"21.5","HomeScore":"24.5","AwaySnaps":"64.62","HomeSnaps":"63.17","LYOppPassDVOA":"28","LYOppRushDVOA":"23","LYHomePassDVOA":"1","LYHomeRushDVOA":"2","TYHOppPassDVOA":"28","TYOppRushDVOA":"23","TYHomePassDVOA":"1","TYHomeRushDVOA":"2"},
    {"Away":"TEN","Home":"CLE","AwayScore":"20","HomeScore":"25.5","AwaySnaps":"61.93","HomeSnaps":"65.98","LYOppPassDVOA":"21","LYOppRushDVOA":"15","LYHomePassDVOA":"7","LYHomeRushDVOA":"25","TYHOppPassDVOA":"21","TYOppRushDVOA":"15","TYHomePassDVOA":"7","TYHomeRushDVOA":"25"},
    {"Away":"BAL","Home":"MIA","AwayScore":"22","HomeScore":"15.5","AwaySnaps":"64.04","HomeSnaps":"65.67","LYOppPassDVOA":"3","LYOppRushDVOA":"6","LYHomePassDVOA":"23","LYHomeRushDVOA":"24","TYHOppPassDVOA":"3","TYOppRushDVOA":"6","TYHomePassDVOA":"23","TYHomeRushDVOA":"24"},
    {"Away":"ATL","Home":"MIN","AwayScore":"21.75","HomeScore":"25.75","AwaySnaps":"62.07","HomeSnaps":"61.99","LYOppPassDVOA":"29","LYOppRushDVOA":"30","LYHomePassDVOA":"5","LYHomeRushDVOA":"11","TYHOppPassDVOA":"29","TYOppRushDVOA":"30","TYHomePassDVOA":"5","TYHomeRushDVOA":"11"},
    {"Away":"BUF","Home":"NYJ","AwayScore":"18.5","HomeScore":"21.5","AwaySnaps":"65.13","HomeSnaps":"57.96","LYOppPassDVOA":"2","LYOppRushDVOA":"14","LYHomePassDVOA":"18","LYHomeRushDVOA":"21","TYHOppPassDVOA":"2","TYOppRushDVOA":"14","TYHomePassDVOA":"18","TYHomeRushDVOA":"21"},
    {"Away":"WAS","Home":"PHI","AwayScore":"18.25","HomeScore":"27.75","AwaySnaps":"59.71","HomeSnaps":"64.69","LYOppPassDVOA":"11","LYOppRushDVOA":"28","LYHomePassDVOA":"15","LYHomeRushDVOA":"9","TYHOppPassDVOA":"11","TYOppRushDVOA":"28","TYHomePassDVOA":"15","TYHomeRushDVOA":"9"},
    {"Away":"LAR","Home":"CAR","AwayScore":"26.75","HomeScore":"23.75","AwaySnaps":"64.94","HomeSnaps":"61.66","LYOppPassDVOA":"9","LYOppRushDVOA":"27","LYHomePassDVOA":"24","LYHomeRushDVOA":"18","TYHOppPassDVOA":"9","TYOppRushDVOA":"27","TYHomePassDVOA":"24","TYHomeRushDVOA":"18"},
    {"Away":"KC","Home":"JAC","AwayScore":"28.25","HomeScore":"24.25","AwaySnaps":"65.39","HomeSnaps":"65.43","LYOppPassDVOA":"12","LYOppRushDVOA":"32","LYHomePassDVOA":"6","LYHomeRushDVOA":"7","TYHOppPassDVOA":"12","TYOppRushDVOA":"32","TYHomePassDVOA":"6","TYHomeRushDVOA":"7"},
    {"Away":"IND","Home":"LAC","AwayScore":"19","HomeScore":"25.5","AwaySnaps":"63.57","HomeSnaps":"59.95","LYOppPassDVOA":"20","LYOppRushDVOA":"4","LYHomePassDVOA":"10","LYHomeRushDVOA":"10","TYHOppPassDVOA":"20","TYOppRushDVOA":"4","TYHomePassDVOA":"10","TYHomeRushDVOA":"10"},
    {"Away":"CIN","Home":"SEA","AwayScore":"17.25","HomeScore":"26.75","AwaySnaps":"61.77","HomeSnaps":"63.74","LYOppPassDVOA":"25","LYOppRushDVOA":"26","LYHomePassDVOA":"14","LYHomeRushDVOA":"17","TYHOppPassDVOA":"25","TYOppRushDVOA":"26","TYHomePassDVOA":"14","TYHomeRushDVOA":"17"},
    {"Away":"NYG","Home":"DAL","AwayScore":"19.25","HomeScore":"26.25","AwaySnaps":"61.76","HomeSnaps":"64.21","LYOppPassDVOA":"26","LYOppRushDVOA":"20","LYHomePassDVOA":"16","LYHomeRushDVOA":"5","TYHOppPassDVOA":"26","TYOppRushDVOA":"20","TYHomePassDVOA":"16","TYHomeRushDVOA":"5"},
    {"Away":"DET","Home":"ARI","AwayScore":"25","HomeScore":"22.5","AwaySnaps":"62.65","HomeSnaps":"62.05","LYOppPassDVOA":"31","LYOppRushDVOA":"13","LYHomePassDVOA":"8","LYHomeRushDVOA":"29","TYHOppPassDVOA":"31","TYOppRushDVOA":"13","TYHomePassDVOA":"8","TYHomeRushDVOA":"29"},
    {"Away":"SF","Home":"TB","AwayScore":"24.5","HomeScore":"25.5","AwaySnaps":"60.28","HomeSnaps":"64.24","LYOppPassDVOA":"27","LYOppRushDVOA":"12","LYHomePassDVOA":"30","LYHomeRushDVOA":"31","TYHOppPassDVOA":"27","TYOppRushDVOA":"12","TYHomePassDVOA":"30","TYHomeRushDVOA":"31"},
    {"Away":"PIT","Home":"NE","AwayScore":"22.5","HomeScore":"28.5","AwaySnaps":"63.16","HomeSnaps":"65.53","LYOppPassDVOA":"17","LYOppRushDVOA":"8","LYHomePassDVOA":"13","LYHomeRushDVOA":"19","TYHOppPassDVOA":"17","TYOppRushDVOA":"8","TYHomePassDVOA":"13","TYHomeRushDVOA":"19"},
    {"Away":"HOU","Home":"NO","AwayScore":"23.25","HomeScore":"30.25","AwaySnaps":"60.85","HomeSnaps":"64","LYOppPassDVOA":"19","LYOppRushDVOA":"1","LYHomePassDVOA":"22","LYHomeRushDVOA":"3","TYHOppPassDVOA":"19","TYOppRushDVOA":"1","TYHomePassDVOA":"22","TYHomeRushDVOA":"3"},
    {"Away":"DEN","Home":"OAK","AwayScore":"22","HomeScore":"21","AwaySnaps":"64.77","HomeSnaps":"63.8","LYOppPassDVOA":"4","LYOppRushDVOA":"16","LYHomePassDVOA":"32","LYHomeRushDVOA":"22","TYHOppPassDVOA":"4","TYOppRushDVOA":"16","TYHomePassDVOA":"32","TYHomeRushDVOA":"22"}
    ]
    
    

    
    export default gameSummary